### ISSUE TITLE
Problem with libcluster, unable to connect

### ISSUE THREAD

**Issue by jtormey** [alexgaribay/libcluster_gae#2] opened 2019-11-10 20:48 UTC
After following the README instructions, deployed instances are unable to connect to each other. The logs show warnings like this every 10s (the default polling interval):

```
2019-11-10 19:57:15 default[20191110t125255]  19:57:15.990 [warn] [libcluster:my_app] unable to connect to :"my_app@aef-default-20191110t125255-r2jt.c.my-project.internal"
```

I've set `VmDnsSetting=GlobalOnly` in `Cloud Console > Compute Engine > Metadata`, which did not seem to change anything.

What's strange is that now with `-name` configured in `vm.args`, I'm not able to attach to a running instance of my app from inside its container:

```
justin@aef-default-20191110t125255-r2jt ~ $ docker exec -it 17a5a0e7dbd1 /bin/bash
root@17a5a0e7dbd1:/app# ./bin/my_app remote_console
Could not contact remote node my_app@aef-default-20191110t125255-r2jt.c.my-project.internal, reason: :nodedown. Aborting...
```

However, the application is definitely running, it's accessible and can be interacted with. It seems like I'm missing something when it comes to configuring the Erlang VM, or maybe with configuring GAE. Any help would be appreciated!

**Comment by alexgaribay** [comment] 2020-03-20 02:49
Duplicate of #1.

**Closed as completed by alexgaribay** 2020-03-20 02:49 UTC
